version: '3'
services:
  motioneye:
    image: ccrisan/motioneye:master-armhf
    container_name: motioneye
    ports:
      - "8765:8765"
      - "8081:8081"
    hostname: motioneye
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/etc/motioneye
      - ./recode:/var/lib/motioneye
    restart: always
    devices:
      - /dev/video0
      - /dev/video1
      - /dev/media2
      # Add more /dev/videoX devices as needed